project:
  type: website
  output-dir: docs
website:
  favicon: images/favicon-website.png
  title: "matt_leary"
  navbar:
    title: matt_leary
    logo: images/logo.png
    logo-alt: A cockrell, similiar to the Tottenham Hotspur logo, in white next 
              to a white vertical line followed by the text matt_leary also in white
    background: "#132257"
    right: 
    - href: posts.html
      text: posts
    - text: resouces
      menu:
      - text: helpful links
        href: resources/resources-links.html
      - text: data notes
        href: resources/resources-notes.html
      - text: cooking recipes
        href: resources/resources-cooking.html        
    - icon: linkedin
      href: https://www.linkedin.com/in/mbleary
    - icon: envelope
      href: mailto:matt.leary@proton.me
    - icon: github
      href: https://github.com/mleary/mattleary-website
  page-footer:
    left: "Blog made by Matt Leary with [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right: "audere est facere"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
resources: 
  - CNAME

