project:
  type: website

website:
  title: "Clever title here"
  navbar:
    background: "#132257"
    right: 
    - href: about.html
      text: About me
    - href: blog.html
      text: Blog
    - icon: github
      aria-label: github
      href: https://github.com/mleary/mattleary-website

    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

