project:
  type: website
  output-dir: docs
website:
  favicon: images/favicon.png
  title: "matt_leary"
  navbar:
    background: "#132257"
    right: 
    - href: posts.html
      text: posts
    - icon: github
      aria-label: github
      href: https://github.com/mleary/mattleary-website
  page-footer:
    left: "Blog made by Matt Leary with [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right: 
      - icon: github
        aria-label: github
        href: https://github.com/mleary/mattleary-website
      - icon: envelope
        href: mailto:matt.leary@proton.me
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
resources: 
  - CNAME

